apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: time-bound-resource-creation
  labels: 
    app: kyverno
  annotations:
    policies.kyverno.io/severity: medium
    policies.kyverno.io/category: Change Freeze Violation
spec:
  rules:
    - name: validate-time-bound-creation
      match:
        all:
        - (values(Resources)[?Type == 'AWS::ECS::TaskDefinition'] | length(@) > `0`): true
      assert: 
        all:
          - message : "Resource creation is only allowed between January 1 and January 31, 2025 due to change freeze"
            check: 
              (time_between(time_now_utc(),'2025-01-01T00:00:00Z','2025-01-31T23:59:59Z')) : true
