apiVersion: json.kyverno.io/v1alpha1
kind: ValidatingPolicy
metadata:
  name: validate-region
  labels:
    app: kyverno
  annotations:
    policies.kyverno.io/category: CDK Best Practices for ECS
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      When managing containers within AWS ECS, it's crucial to enforce security measures to prevent unauthorized modifications.
      One significant aspect is ensuring the resources are deployed to the 'us-west-1' region. 
      This policy checks if ECS Containers are configured to be deployed in 'us-west-1'.
spec:
  rules:
    - name: validate-region
      match:
        all:
        - (values(Resources)[?Type == 'AWS::ECS::TaskDefinition'] | length(@) > `0`): true
      assert:
        all:
        - message: ECS Containers should only be deployed in us-west-1 region.
          check:
            ~.(values(Resources)[?Type == 'AWS::ECS::TaskDefinition']):
                Properties:
                    ~.(ContainerDefinitions[]):
                        (LogConfiguration.Options):                   
                          awslogs-region: "us-west-1"
